version: 2.1
jobs: # collection of steps
  build:
    docker: 
      - image: circleci/node:10.16.3 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory (special step)
      - run: echo "hello world" # run the `echo` command
      - run: 
          name: install npm packages
          command: npm install
      - run:
          name: run test suite
          command: npm test
      - run:
          name: compile front end
          command: npm run-script build-client
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    docker: 
      - image: circleci/node:10.16.3
    steps:
      - attach_workspace:
          at: .
      - run:
          name: test
          command: pwd
      - run: 
          name: Deploy Master to Firebase
          command: /home/circleci/project/node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build