version: 2.1
jobs: # collection of steps
  build:
    docker: 
      - image: circleci/node:10.16.3 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory (special step)
      - run: echo "hello world" # run the `echo` command
      - run: 
          name: install npm packages
          command: npm install
      - run:
          name: run test suite
          command: npm test


